version: "3.0"
services:
  db:
    image: postgres
    volumes:
      - /data:/var/lib/postgresql/data
    environment:
      "POSTGRES_DB": django_evm_indexer
      "POSTGRES_USER": django_evm_indexer
      "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}"
    networks:
      - django_indexer_default

  indexer_api:
    privileged: true
    image: django_evm_indexer
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /indexer_static:/indexer_static
    environment:
      "POSTGRES_DB": django_evm_indexer
      "POSTGRES_USER": django_evm_indexer
      "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}"
      "POSTGRES_HOST": db
      "POSTGRES_PORT": 5432
      "SUPERUSER_USERNAME": "${SUPERUSER_USERNAME}"
      "SUPERUSER_PASSWORD": "${SUPERUSER_PASSWORD}"
    command: [ "/bin/sh", "run_api.sh" ]
    networks:
      - django_indexer_default

  nginx:
    build: nginx
    volumes:
      - /ssl:/ssl
      - /indexer_static:/indexer_static
    ports:
      - "80:80"
      - "443:443"
    networks:
      - django_indexer_default

networks:
  django_indexer_default:
    # noinspection ComposeUnknownKeys
    name: django_indexer_default
    driver: bridge

