# Generated by Django 4.2.1 on 2023-06-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexer',
            name='strategy_params',
            field=models.JSONField(null=True, verbose_name="Configure indexer's strategy using JSON dict"),
        ),
    ]
