# Generated by Django 4.2.1 on 2023-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0002_alter_indexer_strategy_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexer',
            name='long_sleep_seconds',
            field=models.PositiveBigIntegerField(default=5, help_text='Indexer will sleep this time if no new blocks in blockchain by the moment'),
        ),
        migrations.AlterField(
            model_name='indexer',
            name='short_sleep_seconds',
            field=models.PositiveBigIntegerField(default=1, help_text='Short sleep is time between two filter requests to blockchain'),
        ),
    ]
