# Generated by Django 4.2.1 on 2023-06-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0003_alter_indexer_long_sleep_seconds_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('address', 'network')},
        ),
    ]
