# Generated by Django 4.2.1 on 2023-06-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0004_alter_token_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexer',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=255),
        ),
    ]
