# Generated by Django 4.2.1 on 2023-06-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0005_indexer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexer',
            name='strategy_params',
            field=models.JSONField(blank=True, null=True, verbose_name="Configure indexer's strategy using JSON dict"),
        ),
    ]
