# Generated by Django 4.2.1 on 2023-06-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0006_alter_indexer_strategy_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexer',
            name='strategy',
            field=models.CharField(choices=[('recipient', 'Recipient'), ('sender', 'Sender'), ('token_scan', 'Token Scan'), ('tokenomics', 'Tokenomics'), ('specified_holders', 'Specified Holders'), ('transfers_participants', 'Transfers Participants')], max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('native', 'Native'), ('erc20', 'Erc20'), ('erc721', 'Erc721'), ('erc721enumerable', 'Erc721Enumerable'), ('erc777', 'Erc777'), ('erc1155', 'Erc1155')], max_length=255),
        ),
    ]
