# Generated by Django 4.2.1 on 2023-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0007_alter_indexer_strategy_alter_token_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexer',
            name='type',
            field=models.CharField(choices=[('transfer_indexer', 'Transfer Indexer'), ('balance_indexer', 'Balance Indexer')], default='transfer_indexer', max_length=255),
        ),
    ]
