# Generated by Django 4.2.1 on 2023-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0008_indexer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenbalance',
            old_name='token',
            new_name='token_instance',
        ),
        migrations.AddField(
            model_name='tokenbalance',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AddField(
            model_name='tokenbalance',
            name='token_id',
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
    ]
