# Generated by Django 4.2.1 on 2023-06-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0009_rename_token_tokenbalance_token_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='explorer_url',
            field=models.CharField(default='', help_text="Provide root URL of explorer with no trailing slash. Example: 'https://etherscan.io'", max_length=2550),
        ),
        migrations.AlterField(
            model_name='indexer',
            name='status',
            field=models.CharField(choices=[('on', 'Active'), ('off', 'Disabled')], default='off', max_length=255),
        ),
        migrations.AlterField(
            model_name='indexer',
            name='strategy',
            field=models.CharField(choices=[('recipient', 'Recipient'), ('sender', 'Sender'), ('token_scan', 'Scan transfers (all transfers are saved)'), ('tokenomics', 'Tokenomics parameters'), ('specified_holders', 'Specified holders'), ('transfers_participants', 'Transfer participants')], max_length=255),
        ),
        migrations.AlterField(
            model_name='indexer',
            name='type',
            field=models.CharField(choices=[('transfer_indexer', 'Transfer indexer'), ('balance_indexer', 'Balance indexer')], default='transfer_indexer', max_length=255),
        ),
        migrations.AlterField(
            model_name='network',
            name='type',
            field=models.CharField(choices=[('filterable', 'Filterable eth_filter'), ('no_filters', 'No filters supported')], max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(help_text='Should be kebab-case. Example: usdt-ethereum-indexer', max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='strategy',
            field=models.CharField(choices=[('event_based_transfer', 'Event-based transfers'), ('receipt_based_transfer', 'Receipt-based transfers')], help_text='Use receipt based transfer strategy with native token. Note: it can be very slow to index', max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('native', 'Native'), ('erc20', 'ERC20 Fungible token'), ('erc721', 'NFT ERC721'), ('erc721enumerable', 'NFT ERC721Enumerable'), ('erc777', 'ERC777 Fungible token'), ('erc1155', 'ERC1155 collection token')], help_text='Options erc721 and erc721enumerable are the same if token is indexed only by transfers (not balances).', max_length=255),
        ),
    ]
