# Generated by Django 4.2.1 on 2023-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0010_network_explorer_url_alter_indexer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='explorer_url',
            field=models.CharField(blank=True, default='', help_text="Provide root URL of explorer with no trailing slash. Example: 'https://etherscan.io'", max_length=2550),
        ),
    ]
