# Generated by Django 4.2.1 on 2023-06-14 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0011_alter_network_explorer_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenbalance',
            options={'verbose_name': 'Balance'},
        ),
        migrations.AlterModelOptions(
            name='tokentransfer',
            options={'verbose_name': 'Transfer'},
        ),
        migrations.AlterField(
            model_name='network',
            name='rpc_url',
            field=models.CharField(max_length=2550, validators=[django.core.validators.RegexValidator(regex='https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\x08([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)')]),
        ),
    ]
