# Generated by Django 4.2.1 on 2023-06-14 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0012_alter_tokenbalance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='rpc_url',
            field=models.CharField(max_length=2550, validators=[django.core.validators.URLValidator()]),
        ),
    ]
