# Generated by Django 4.2.1 on 2023-06-14 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0014_alter_network_rpc_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexer',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='[a-z0-9-]+')]),
        ),
        migrations.AlterField(
            model_name='network',
            name='explorer_url',
            field=models.CharField(blank=True, default='', help_text="Provide root URL of explorer with no trailing slash. Example: 'https://etherscan.io'", max_length=2550, validators=[django.core.validators.URLValidator(schemes=('http', 'https'))]),
        ),
    ]
