# Generated by Django 4.2.1 on 2023-06-14 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0015_alter_indexer_name_alter_network_explorer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexer',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')]),
        ),
    ]
