# Generated by Django 4.2.1 on 2023-06-14 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0016_alter_indexer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexer',
            name='name',
            field=models.CharField(help_text='Name should be a valid container identifier. Example: <code>polygon-mainnet-usdt-tracker</code>', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='token',
            name='address',
            field=models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')]),
        ),
    ]
