# Generated by Django 4.2.1 on 2023-06-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0019_tokentransfer_fetched_by_alter_indexer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbalance',
            name='tracked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_balances', to='indexer_api.indexer'),
        ),
    ]
