# Generated by Django 4.2.1 on 2023-06-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0020_tokenbalance_tracked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentransfer',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indexer',
            name='status',
            field=models.CharField(choices=[('on', 'Active'), ('off', 'Disabled')], default='off', help_text='You can change status using Admin Actions on Indexers admin panel', max_length=255),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenbalance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AlterField(
            model_name='tokenbalance',
            name='token_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True),
        ),
    ]
