# Generated by Django 4.2.1 on 2023-06-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_api', '0022_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokentransfer',
            name='event_date',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
